### ISSUE TITLE
Code generated with protoc-gen-swift 1.29.0 (and earlier) doesn't compile with 1.30.0 runtime

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-protobuf#1830]
The API for name maps between the runtime and generated code changed in 1.30.0 which in some cases leads to build failures when the runtime version is 1.29.0 or earlier.

Normally, I think [the compatibility version is bumped](https://github.com/apple/swift-protobuf/blob/c7a162b1a0f24fcad9aafa83e87dd7b010495ede/Sources/protoc-gen-swift/Version.swift#L22-L28) to make this obvious but that didn't happen this time around.

Here's a minimal producer:

```proto
syntax = "proto3";

message Hello {
  reserved 1;
}
```

You get the following error if generating with protoc-gen-swift 1.30.0 and using the 1.29.0 or earlier runtime:

```
/Users/georgebarnett/Desktop/does-it-build/Sources/does-it-build/hello.pb.swift:37:56: error: argument passed to call that takes no arguments
35 | extension Hello: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
36 |   static let protoMessageName: String = "Hello"
37 |   static let _protobuf_nameMap = SwiftProtobuf._NameMap(
   |                                                        `- error: argument passed to call that takes no arguments
38 |       reservedNames: [],
39 |       reservedRanges: [1..<2],
/Users/georgebarnett/Desktop/does-it-build/Sources/does-it-build/hello.pb.swift:37:56: error: argument passed to call that takes no arguments
35 | extension Hello: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
36 |   static let protoMessageName: String = "Hello"
37 |   static let _protobuf_nameMap = SwiftProtobuf._NameMap(
   |                                                        `- error: argument passed to call that takes no arguments
38 |       reservedNames: [],
39 |       reservedRanges: [1..<2],
```

**Comment by thomasvl** [comment]
We ensure the current version of the runtime can work with older generated code, but not the other way around.  You are using newly generated code with an older version of the runtime.  i.e. - your version of the plugin is newer than the runtime you are trying to link against.

The compatibility version only has to get changed when we break that first part (old code with current runtime).

**Comment by thomasvl** [comment]
ps - if we bumped the compatibility it's effectively is a breaking change (major version) because then old code can't work.  ObjC deals with this by having two CPP constants - "current version" and "min version" supported by the runtime, then the generated code can have checks against bot. But there's no way to do something like that with Swift.

The other choice would be to rev something like our compatibility marker with *every* release, which is the path upstream C++ has moved too.

**Comment by glbrntt** [comment]
> We ensure the current version of the runtime can work with older generated code, but not the other way around. You are using newly generated code with an older version of the runtime. i.e. - your version of the plugin is newer than the runtime you are trying to link against.
> 
> The compatibility version only has to get changed when we break that first part (old code with current runtime).

That's what I expected, but the text around the compatibility version made me think otherwise.

> The other choice would be to rev something like our compatibility marker with every release, which is the path upstream C++ has moved too.

I've observed that users often have a code-gen/runtime mismatch because they install `protoc-gen-swift` via homebrew (we advise against this for gRPC Swift). Bumping the compat marker would be a good forcing function to get users to build `protoc-gen-swift` at the same version as their SwiftProtobuf dependency. That's probably fine if you have a Swift Package (because you can do `swift build --product protoc-gen-swift`) but I don't think there's an equivalent mechanism if you add a Swift Package as a dependency to an xcodeproj.

**Comment by thomasvl** [comment]
> I've observed that users often have a code-gen/runtime mismatch because they install `protoc-gen-swift` via homebrew (we advise against this for gRPC Swift).

Yea, with a preprocessor we could provide better messaging for it (#warning/#error/etc), I don't think I've seen anyone come up with something for Swift.

> Bumping the compat marker would be a good forcing function to get users to build `protoc-gen-swift` at the same version as their SwiftProtobuf dependency.

The the number there is sorta not true in that it leads one to think it is _just a number_, but if you look at what actually does the enforcement: https://github.com/apple/swift-protobuf/blob/c7a162b1a0f24fcad9aafa83e87dd7b010495ede/Sources/SwiftProtobuf/ProtobufAPIVersionCheck.swift#L22-L42, we're changing the type. So:

1. We're always at the mercy of a missing type error which is always somewhat cryptic. 😦 
2. We might be able to do a model where we don't do the `ProtobufAPIVersionCheck` naming with an associated type, but instead just went for a new (numbered?) protocol/type and directly output something referencing it in each file, that way we could "export" support for "multiple" versions, but the current model where the associated type changes would is what leads to a breaking change with a version bump.

> That's probably fine if you have a Swift Package (because you can do `swift build --product protoc-gen-swift`) but I don't think there's an equivalent mechanism if you add a Swift Package as a dependency to an xcodeproj.

I guess to use the plugin from the package they would have to use a Package.swift and now a "direct" Xcode project?  Sounds like file as a request with Apple/Xcode.  😇

**Comment by glbrntt** [comment]
> , we're changing the type. So:
> 1. We're always at the mercy of a missing type error which is always somewhat cryptic. 😦
> 2. We might be able to do a model where we don't do the `ProtobufAPIVersionCheck` naming with an associated type, but instead just went for a new (numbered?) protocol/type and directly output something referencing it in each file, that way we could "export" support for "multiple" versions, but the current model where the associated type changes would is what leads to a breaking change with a version bump.

Yeah, agreed, it's not a great experience if the current versioning check fails.

Exporting a version somehow would be great but I'm not sure Swift offers a neat way to do this at compile time yet.

> > That's probably fine if you have a Swift Package (because you can do `swift build --product protoc-gen-swift`) but I don't think there's an equivalent mechanism if you add a Swift Package as a dependency to an xcodeproj.
> 
> I guess to use the plugin from the package they would have to use a Package.swift and now a "direct" Xcode project? Sounds like file as a request with Apple/Xcode. 😇

Turns out I was wrong: when you add the `swift-protobuf` package as a dependency to an xcodeproj you can choose for `protoc-gen-swift` to be included as well (it isn't by default). You can then access it from a custom build phase.

**Comment by thomasvl** [comment]
> Exporting a version somehow would be great but I'm not sure Swift offers a neat way to do this at compile time yet.

Horrible idea: We make a macro, and it takes arguments, the macro does the validation and thus can write out it's own custom fail message.

> > I guess to use the plugin from the package they would have to use a Package.swift and now a "direct" Xcode project? Sounds like file as a request with Apple/Xcode. 😇
> 
> Turns out I was wrong: when you add the `swift-protobuf` package as a dependency to an xcodeproj you can choose for `protoc-gen-swift` to be included as well (it isn't by default). You can then access it from a custom build phase.

Nice!  Can you do a PR to add documentation for folks on how to do that?  (Although they still need a `protoc` binary on their path)

**Comment by glbrntt** [comment]
> Horrible idea: We make a macro, and it takes arguments, the macro does the validation and thus can write out it's own custom fail message.

A Swift macro? That'd bring along a dependency on swift-syntax which wouldn't be great...
 
> > > I guess to use the plugin from the package they would have to use a Package.swift and now a "direct" Xcode project? Sounds like file as a request with Apple/Xcode. 😇
> > 
> > 
> > Turns out I was wrong: when you add the `swift-protobuf` package as a dependency to an xcodeproj you can choose for `protoc-gen-swift` to be included as well (it isn't by default). You can then access it from a custom build phase.
> 
> Nice! Can you do a PR to add documentation for folks on how to do that? (Although they still need a `protoc` binary on their path)

I will at some point, I just need to find enough time to do it.

**Comment by thomasvl** [comment]
> > Horrible idea: We make a macro, and it takes arguments, the macro does the validation and thus can write out it's own custom fail message.
> 
> A Swift macro? That'd bring along a dependency on swift-syntax which wouldn't be great...

I did say it was a _horrible_ idea…  😇

**Comment by thomasvl** [comment]
Closing as I think we landed on this is what is expect as there's nothing better that can be done (like how protobuf for C based does a min/max check to provider better error checking via the preprocessor).
