### ISSUE TITLE
Carthage build failure

### ISSUE THREAD

**Issue by SebastianThiebaud** [apple/swift-protobuf#668]
- Operating system: macOS 10.13 (17A365)
- Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)
- Protoc compiler: libprotoc 3.4.0
- Using `github "apple/swift-protobuf" "0.9.903"` 

When running `carthage bootstrap --platform 'iOS'`, build failed and log shows these errors:

```
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/Message+JSONAdditions.swift:60:14: error: use of undeclared type 'JSONDecodingOptions'
    options: JSONDecodingOptions = JSONDecodingOptions()
             ^~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/Message+JSONAdditions.swift:83:14: error: use of undeclared type 'JSONDecodingOptions'
    options: JSONDecodingOptions = JSONDecodingOptions()
             ^~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/JSONDecoder.swift:28:62: error: use of undeclared type 'JSONDecodingOptions'
  internal init(source: UnsafeBufferPointer<UInt8>, options: JSONDecodingOptions) {
                                                             ^~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/JSONDecoder.swift:19:25: error: use of undeclared type 'JSONDecodingOptions'
  internal var options: JSONDecodingOptions
                        ^~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/JSONDecoder.swift:569:15: error: non-nominal type 'M' does not support explicit initialization
      value = M()
              ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/JSONDecoder.swift:601:23: error: non-nominal type 'M' does not support explicit initialization
        var message = M()
                      ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/Message+JSONArrayAdditions.swift:61:14: error: use of undeclared type 'JSONDecodingOptions'
    options: JSONDecodingOptions = JSONDecodingOptions()
             ^~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/Message+JSONArrayAdditions.swift:84:14: error: use of undeclared type 'JSONDecodingOptions'
    options: JSONDecodingOptions = JSONDecodingOptions()
             ^~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDecoder.swift:838:21: error: non-nominal type 'M' does not support explicit initialization
            value = M()
                    ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDecoder.swift:850:24: error: non-nominal type 'M' does not support explicit initialization
        var newValue = M()
                       ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDecoder.swift:857:30: error: non-nominal type 'G' does not support explicit initialization
        var group = value ?? G()
                             ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDecoder.swift:865:21: error: non-nominal type 'G' does not support explicit initialization
        var group = G()
                    ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDecoder.swift:1004:55: error: non-nominal type 'ValueType' does not support explicit initialization
        value[k ?? KeyType.proto3DefaultValue] = v ?? ValueType()
                                                      ^~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:55:34: error: use of undeclared type 'JSONDecodingOptions'
                        options: JSONDecodingOptions,
                                 ^~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:122:28: error: use of undeclared type 'JSONDecodingOptions'
    case contentJSON(Data, JSONDecodingOptions)
                           ^~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:97:13: error: pattern cannot match values of type 'AnyMessageStorage.InternalState'
      case .contentJSON(let contentJSON, let options):
           ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:152:20: error: non-nominal type 'M' does not support explicit initialization
      target = try M(serializedData: data, extensions: extensions, partial: true)
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:161:22: error: non-nominal type 'M' does not support explicit initialization
        target = try M(serializedData: data, extensions: extensions, partial: true)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:164:11: error: pattern cannot match values of type 'AnyMessageStorage.InternalState'
    case .contentJSON(let contentJSON, let options):
         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:187:11: error: pattern cannot match values of type 'AnyMessageStorage.InternalState'
    case .contentJSON:
         ~^~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:251:11: error: pattern cannot match values of type 'AnyMessageStorage.InternalState'
    case .contentJSON(let contentJSON, let options):
         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:339:14: error: pattern cannot match values of type 'AnyMessageStorage.InternalState'
    if case .contentJSON(let myJSON, _) = state,
            ~^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:340:14: error: pattern cannot match values of type 'AnyMessageStorage.InternalState'
       case .contentJSON(let otherJSON, _) = other.state,
            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/AnyMessageStorage.swift:383:11: error: pattern cannot match values of type 'AnyMessageStorage.InternalState'
    case .contentJSON(let contentJSON, _):
         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/Message.swift:176:19: error: non-nominal type 'Self' does not support explicit initialization
    var message = Self()
                  ^~~~~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/TextFormatDecoder.swift:490:21: error: non-nominal type 'M' does not support explicit initialization
            value = M()
                    ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/TextFormatDecoder.swift:524:35: error: non-nominal type 'M' does not support explicit initialization
                    var message = M()
                                  ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/TextFormatDecoder.swift:538:31: error: non-nominal type 'M' does not support explicit initialization
                var message = M()
                              ^~~
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/TextFormatScanner.swift:73:30: error: '+' is deprecated: Please use explicit type conversions or Strideable methods for mixed-type arithmetics.
      return c - asciiUpperA + 10
                             ^
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/TextFormatScanner.swift:76:30: error: '+' is deprecated: Please use explicit type conversions or Strideable methods for mixed-type arithmetics.
      return c - asciiLowerA + 10
                             ^
/Users/sebastianthiebaud/Repositories/sample-app/Carthage/Checkouts/swift-protobuf/Sources/SwiftProtobuf/JSONScanner.swift:68:14: error: '-' is deprecated: Please use explicit type conversions or Strideable methods for mixed-type arithmetics.
    return n - 48
             ^
```

Am I missing something obvious? Thank you.

**Comment by thomasvl** [comment]
If you are trying to use Swift 4, I'd suggest starting with tag 0.905, since that does have some Swift 4 fixes.

**Comment by SebastianThiebaud** [comment]
Thank you @thomasvl! I was following the `master` readme instructions. Carthage was able to build with `0.9.905`.

**Comment by thomasvl** [comment]
The text talks about picking the release tag you want to use, the problem is in those example blocks need _something_ but we also don't want to have to ref all the directions with every release.   Not sure how to provide an example that folks won't directly copy paste. 🙁

**Comment by SebastianThiebaud** [comment]
Totally understandable. Maybe adding a comment for Swift 4 would avoid having more people making this mistake?
