### PR TITLE
Sources: remove now deprecated 'characters'

### PR DESCRIPTION
**Pull request by zllak**
With latest Swift version and Xcode (9.1 beta), using `characters` now generates an error
```
Apple Swift version 4.0.1 (swiftlang-900.0.68 clang-900.0.38)
Target: x86_64-apple-macosx10.9
```

### CODE REVIEW

**Comment by thomasvl** [comment]
Out stated goal is to always support a full version back: https://github.com/apple/swift-protobuf/blob/master/Documentation/INTERNALS.md#swift-language-support

So will these changes still build with 3.0.x or will we need to do conditionals like in other parts of the code to properly make that still build with all versions?

**Comment by tbkka** [comment]
FYI:  At least using 4-DEV on Ubuntu, these seem to be just warnings for now, so they don't break the build per se.  (We'll still fix them, of course.)

The current DEV snapshot has a few more issues that will need to be looked into.

**Comment by tbkka** [comment]
With these changes, Swift 3.1 is not happy:
```
/home/tkientzle/SwiftProtobuf/BUILDS/swift-protobuf-swift-3.0.1/Sources/SwiftProtobuf/Google_Protobuf_Duration+Extensions.swift:26:15: error: value of type 'String' has no member 'makeIterator'
  var chars = text.makeIterator()
              ^~~~ ~~~~~~~~~~~~
/home/tkientzle/SwiftProtobuf/BUILDS/swift-protobuf-swift-3.1/Sources/SwiftProtobuf/Google_Protobuf_FieldMask+Extensions.swift:46:12: error: type 'String' does not conform to protocol 'Sequence'
  for c in name {
           ^
/home/tkientzle/SwiftProtobuf/BUILDS/swift-protobuf-swift-3.1/Sources/SwiftProtobuf/Google_Protobuf_FieldMask+Extensions.swift:64:23: error: type 'String' does not conform to protocol 'Sequence'
  for c: Character in names {
                      ^
/home/tkientzle/SwiftProtobuf/BUILDS/swift-protobuf-swift-3.1/Sources/SwiftProtobuf/Google_Protobuf_Duration+Extensions.swift:26:15: error: value of type 'String' has no member 'makeIterator'
  var chars = text.makeIterator()
              ^~~~ ~~~~~~~~~~~~
/home/tkientzle/SwiftProtobuf/BUILDS/swift-protobuf-swift-3.1/Sources/SwiftProtobuf/NameMap.swift:27:14: error: type 'String' does not conform to protocol 'Sequence'
    for c in s {
             ^
/home/tkientzle/SwiftProtobuf/BUILDS/swift-protobuf-swift-3.1/Sources/SwiftProtobuf/Google_Protobuf_Any+Registry.swift:24:28: error: value of type 'String' has no member 'last'
  if typePrefix.isEmpty || typePrefix.last != "/" {
                           ^~~~~~~~~~ ~~~~
```

**Comment by NachoSoto** [comment]
These are now deprecated in `Swift 4.0.2` (in `Xcode 9.1`):
```

**Comment by rick-kln** [comment]
Yeah the deprecation in `Swift 4.0.2` and `Xcode 9.1` means that if you try and build via Carthage for `Xcode 9.1` swift-protobuf will crash the carthage build. 

Workaround as it stands is to make these changes locally and manually build the swift-protobuf framework.

**Comment by thomasvl** [comment]
> crash the carthage build

?  like there is a compiler bug it is tripping up? Or do you just mean the build is failing with an error?

**Comment by rick-kln** [comment]
Yeah sorry the build just fails with an error :)

**Comment by tbkka** [comment]
I have a local fix for this but it's not yet fully tested.

**Comment by tbkka** [comment]
#692 expands this with `#if swift` conditionals.  I've tested that version with various Swift 3 compilers but haven't yet updated with the latest Swift 4.

**Comment by tarunon** [comment]
Swift 3.2 also deprecated `characters`, I think `#if swift(>=3.2)` is better.
